#!/usr/bin/env python
num=raw_input(' please input > ') 
N=int(num,10)  
number=0
for i in range(1,N+1):
 count=0
 for j in range(1,i+1):
  b=i%j
  if b==0:
   count=count+1

 if count==2:
  number=number+1

print(number)

